Issue 2 user can view entries
wang-morris/code-journal pull request #6
Opened 2022-07-19 04:11 UTC by wang-morris

https://user-images.githubusercontent.com/103090771/179662860-4fbf7bf3-a809-4577-8728-e9ab748c46cd.mp4

2022-07-19 04:17 UTC, Zhiwutian requested changes
1 tiny update!

2022-07-19 04:17 UTC, Zhiwutian commented on js/main.js
> +  $ul.append(renderData(submission));
small update, you want to use `prepend` here to add it to the front of the other children of the ul

2022-07-19 05:36 UTC, wang-morris commented
https://user-images.githubusercontent.com/103090771/179673049-e238dc01-eb0a-4bb3-a455-2a33d64c5d43.mp4

2022-07-20 01:32 UTC, Zhiwutian approved these changes
👍🏼

2022-07-20 01:35 UTC, merged